import type { LessonVoiceIssue } from "#nakafa-content/voice/types";

const BLOCKING_RULES = new Set([
  "abstract-concept-question-personification",
  "abrupt-scenario-imperative",
  "blockquote-editorial-label",
  "compressed-renewable-timescale-contrast",
  "corrective-decoration-metaphor",
  "chemical-formula-personification",
  "decorative-picture-to-calculation",
  "duplicate-adjacent-word",
  "em-dash",
  "empty-example-preface",
  "evidence-carrying-metaphor",
  "exact-line-smoothing",
  "external-link-invalid-placement",
  "forbidden-control-character",
  "german-formal-address",
  "heading-symbol",
  "indonesian-mathematical-family-calque",
  "indonesian-detached-discussion-passive",
  "indonesian-meta-discussion-classification",
  "indonesian-ambiguous-calculation-reference",
  "indonesian-attached-dimana",
  "indonesian-bare-modal-adjective",
  "indonesian-bare-visibility-adverb",
  "indonesian-dimensional-container-calque",
  "indonesian-floor-division-calque",
  "indonesian-formal-author-self-reference",
  "indonesian-formal-learner-address",
  "indonesian-plural-learner-address",
  "indonesian-heading-dehyphenated-reduplication",
  "indonesian-informal-slang",
  "indonesian-mechanical-input-constraint-calque",
  "indonesian-nonstandard-affix",
  "indonesian-nonstandard-apapun",
  "indonesian-nonstandard-compound",
  "indonesian-nonstandard-mempengaruhi",
  "indonesian-relative-di-mana",
  "indonesian-stiff-interpret-instruction",
  "indonesian-stiff-serampangan",
  "indonesian-trailing-bare-range",
  "indonesian-uncertainty-propagation-calque",
  "indonesian-unit-cancellation-calque",
  "indonesian-unexplained-regularization-calque",
  "indonesian-water-ratio-gateway",
  "irrelevant-fiction-label",
  "learner-facing-semicolon",
  "locale-representation-parity",
  "malformed-latex-command",
  "plain-math-label",
  "known-decorative-science-heading",
  "redirected-cell-machinery-metaphor",
  "rhetorical-not-only",
  "source-only-heading",
  "source-navigation-filler",
  "unexplained-output-scheduling",
  "unqualified-energy-density-claim",
  "unqualified-fuel-storage-claim",
  "unsupported-evaluative-preface",
  "vague-benefit-risk-reference",
]);

/** Returns true only for objective constraints and proven regressions. */
export function isBlockingLessonVoiceIssue(issue: LessonVoiceIssue): boolean {
  return BLOCKING_RULES.has(issue.rule);
}
