packages:
  - apps/*
  - packages/*

engineStrict: true
savePrefix: ""

catalog:
  '@effect/platform': 0.97.0
  '@effect/platform-node': 0.108.0
  '@mdx-js/mdx': 3.1.1
  '@types/estree-jsx': 1.0.5
  '@types/mdast': 4.0.4
  '@types/unist': 3.0.3
  '@vitest/coverage-istanbul': 4.1.10
  effect: 3.22.0
  eslint-scope: 9.1.2
  estree-util-visit: 2.0.0
  mdast-util-mdx: 3.0.0
  mdast-util-to-string: 4.0.0
  remark-gfm: 4.0.1
  remark-math: 6.0.0
  typescript: npm:@typescript/typescript6@6.0.2
  unified: 11.0.5
  unist-util-visit: 5.1.0
  vitest: 4.1.10

allowBuilds:
  '@parcel/watcher': false
  msgpackr-extract: false
