import { Buffer } from "node:buffer";
import { timingSafeEqual } from "node:crypto";
import type { IncomingMessage, ServerResponse } from "node:http";
import { Sha256HashSchema } from "@nakafa/aksara-contracts/ids";
import {
  LOCAL_PREVIEW_ARTIFACT_PREFIX,
  localPreviewArtifactPath,
} from "@nakafa/aksara-contracts/preview/artifact";
import { previewDocumentRoute } from "@nakafa/aksara-contracts/preview/document";
import {
  LOCAL_PREVIEW_FORMAT,
  type LocalPreviewManifest,
  LocalPreviewManifestSchema,
  PreviewEventSchema,
} from "@nakafa/aksara-contracts/preview/spec";
import {
  type Context,
  Duration,
  Effect,
  Equal,
  Fiber,
  HashMap,
  MutableHashMap,
  Option,
  Schedule,
  Schema,
} from "effect";
import { encodeJsonText } from "#cli/text/json";

export const PREVIEW_MANIFEST_PATH = "/manifest";
export const PREVIEW_EVENTS_PATH = "/events";

const PREVIEW_HEARTBEAT = ": keep-alive\n\n";
const PREVIEW_HEARTBEAT_INTERVAL_MS = 30_000;

const PreviewHttpStateSchema = Schema.Struct({
  artifacts: Schema.HashMap(Sha256HashSchema, Schema.String),
  manifest: LocalPreviewManifestSchema,
  manifestJson: Schema.String,
});

/** Complete immutable state observed by one HTTP request or SSE event. */
export type PreviewHttpState = typeof PreviewHttpStateSchema.Type;

/** Authenticated transport around atomically replaced preview state. */
export interface PreviewHttp {
  /** Ends every open event stream during scoped provider shutdown. */
  readonly close: () => void;
  /** Handles one loopback HTTP request without owning server lifecycle. */
  readonly handle: (request: IncomingMessage, response: ServerResponse) => void;
  /** Broadcasts one already committed state to every live event stream. */
  readonly publish: (state: PreviewHttpState) => void;
}

interface PreviewHttpInput {
  /** Services of the fiber that opened the provider; every heartbeat runs with them. */
  readonly context: Context.Context<never>;
  /** Overrides heartbeat cadence for deterministic transport tests. */
  readonly heartbeatIntervalMs?: number;
  /** Returns the one complete state committed before this request began. */
  readonly readState: () => PreviewHttpState;
  readonly token: string;
}

/** Writes one bounded JSON response with cache and sniffing disabled. */
function writeJson(response: ServerResponse, status: number, body: string) {
  response.writeHead(status, {
    "cache-control": "no-store",
    "content-type": "application/json; charset=utf-8",
    "x-content-type-options": "nosniff",
  });
  response.end(body);
}

/** Compares one bearer header without data-dependent token comparison. */
function hasValidToken(header: string | undefined, token: string) {
  const expected = Buffer.from(`Bearer ${token}`, "utf8");
  const actual = Buffer.from(header ?? "", "utf8");
  return actual.length === expected.length && timingSafeEqual(actual, expected);
}

/** Returns the exact request path without normalizing traversal segments. */
function requestPath(request: IncomingMessage) {
  const url = String(request.url);
  const queryIndex = url.indexOf("?");
  return queryIndex === -1 ? url : url.slice(0, queryIndex);
}

/** Decodes only the canonical hash segment generated by the manifest. */
function decodeArtifactHash(path: string) {
  const encoded = path.slice(LOCAL_PREVIEW_ARTIFACT_PREFIX.length);
  const candidate = encoded.replace("sha256%3A", "sha256:");
  return Schema.decodeOption(Sha256HashSchema)(candidate).pipe(
    Option.filter((hash) => localPreviewArtifactPath(hash) === path)
  );
}

/** Serializes one minimal event from the exact committed manifest. */
function eventJson(manifest: LocalPreviewManifest) {
  return encodeJsonText(
    PreviewEventSchema.make({
      format: LOCAL_PREVIEW_FORMAT,
      revision: manifest.revision,
      route: previewDocumentRoute(manifest.document),
      status: manifest.status,
    })
  );
}

/**
 * Writes one keep-alive line after each full interval until its fiber is
 * interrupted. A write to a peer that is gone does not throw: Node destroys the
 * response and emits `close`, and the `close` handler interrupts this fiber.
 */
const writeKeepAlives = Effect.fn("AksaraCli.writePreviewKeepAlives")(
  (response: ServerResponse, intervalMs: number) => {
    const interval = Duration.millis(intervalMs);
    return Effect.sync(() => response.write(PREVIEW_HEARTBEAT)).pipe(
      Effect.repeat(Schedule.spaced(interval)),
      Effect.delay(interval)
    );
  }
);

/** Creates the authenticated request transport around scoped provider state. */
export function makePreviewHttp(input: PreviewHttpInput): PreviewHttp {
  const clients = MutableHashMap.empty<ServerResponse, Fiber.Fiber<unknown>>();
  /** Forks one fiber with the services of the fiber that opened the provider. */
  const runFork = Effect.runForkWith(input.context);
  /** Interrupts one heartbeat from a Node callback, before its response ends. */
  const stopHeartbeat = (heartbeat: Fiber.Fiber<unknown>) => {
    runFork(Fiber.interrupt(heartbeat));
  };

  /** Handles one authenticated request against one atomic state snapshot. */
  const handle: PreviewHttp["handle"] = (request, response) => {
    if (!hasValidToken(request.headers.authorization, input.token)) {
      writeJson(response, 401, '{"error":"unauthorized"}');
      return;
    }
    if (request.method !== "GET") {
      response.setHeader("allow", "GET");
      writeJson(response, 405, '{"error":"method"}');
      return;
    }
    const path = requestPath(request);
    const state = input.readState();
    if (path === PREVIEW_MANIFEST_PATH) {
      writeJson(response, 200, state.manifestJson);
      return;
    }
    if (path === PREVIEW_EVENTS_PATH) {
      response.writeHead(200, {
        "cache-control": "no-store",
        connection: "keep-alive",
        "content-type": "text/event-stream; charset=utf-8",
      });
      const heartbeat = runFork(
        writeKeepAlives(
          response,
          input.heartbeatIntervalMs ?? PREVIEW_HEARTBEAT_INTERVAL_MS
        )
      );
      MutableHashMap.set(clients, Equal.byReferenceUnsafe(response), heartbeat);
      response.once("close", () => {
        stopHeartbeat(heartbeat);
        MutableHashMap.remove(clients, Equal.byReferenceUnsafe(response));
      });
      response.write(`event: update\ndata: ${eventJson(state.manifest)}\n\n`);
      return;
    }
    if (path.startsWith(LOCAL_PREVIEW_ARTIFACT_PREFIX)) {
      const artifact = decodeArtifactHash(path).pipe(
        Option.flatMap((hash) => HashMap.get(state.artifacts, hash))
      );
      if (Option.isSome(artifact)) {
        writeJson(response, 200, artifact.value);
        return;
      }
      writeJson(response, 409, '{"error":"409"}');
      return;
    }
    writeJson(response, 404, '{"error":"404"}');
  };

  /** Ends every event response without retaining stale scoped clients. */
  const close = () => {
    for (const [client, heartbeat] of clients) {
      stopHeartbeat(heartbeat);
      client.end();
    }
    MutableHashMap.clear(clients);
  };

  /** Notifies every live client after one complete state replacement. */
  const publish = (state: PreviewHttpState) => {
    const event = `event: update\ndata: ${eventJson(state.manifest)}\n\n`;
    for (const client of MutableHashMap.keys(clients)) {
      client.write(event);
    }
  };

  return { close, handle, publish };
}
