import { Buffer } from "node:buffer";
import { timingSafeEqual } from "node:crypto";
import type { IncomingMessage, ServerResponse } from "node:http";
import {
  type Sha256Hash,
  Sha256HashSchema,
} from "@nakafa/aksara-contracts/ids";
import {
  LOCAL_PREVIEW_ARTIFACT_PREFIX,
  localPreviewArtifactPath,
} from "@nakafa/aksara-contracts/preview/artifact";
import { previewDocumentRoute } from "@nakafa/aksara-contracts/preview/document";
import {
  LOCAL_PREVIEW_FORMAT,
  type LocalPreviewManifest,
  PreviewEventSchema,
} from "@nakafa/aksara-contracts/preview/spec";
import { HashMap, Option, Schema } from "effect";

export const PREVIEW_MANIFEST_PATH = "/v1/manifest";
export const PREVIEW_EVENTS_PATH = "/v1/events";

const PREVIEW_HEARTBEAT = ": keep-alive\n\n";
const PREVIEW_HEARTBEAT_INTERVAL_MS = 30_000;

/** Complete immutable state observed by one HTTP request or SSE event. */
export interface PreviewHttpState {
  readonly artifacts: HashMap.HashMap<Sha256Hash, string>;
  readonly manifest: LocalPreviewManifest;
  readonly manifestJson: string;
}

/** Authenticated transport around atomically replaced preview state. */
export interface PreviewHttp {
  /** Ends every open event stream during scoped provider shutdown. */
  readonly close: () => void;
  /** Handles one loopback HTTP request without owning server lifecycle. */
  readonly handle: (request: IncomingMessage, response: ServerResponse) => void;
  /** Broadcasts one already committed state to every live event stream. */
  readonly publish: (state: PreviewHttpState) => void;
}

interface PreviewHttpInput {
  /** Overrides heartbeat cadence for deterministic transport tests. */
  readonly heartbeatIntervalMs?: number;
  /** Returns the one complete state committed before this request began. */
  readonly readState: () => PreviewHttpState;
  readonly token: string;
}

/** Writes one bounded JSON response with cache and sniffing disabled. */
function writeJson(response: ServerResponse, status: number, body: string) {
  response.writeHead(status, {
    "cache-control": "no-store",
    "content-type": "application/json; charset=utf-8",
    "x-content-type-options": "nosniff",
  });
  response.end(body);
}

/** Compares one bearer header without data-dependent token comparison. */
function hasValidToken(header: string | undefined, token: string) {
  const expected = Buffer.from(`Bearer ${token}`, "utf8");
  const actual = Buffer.from(header ?? "", "utf8");
  return actual.length === expected.length && timingSafeEqual(actual, expected);
}

/** Returns the exact request path without normalizing traversal segments. */
function requestPath(request: IncomingMessage) {
  const url = String(request.url);
  const queryIndex = url.indexOf("?");
  return queryIndex === -1 ? url : url.slice(0, queryIndex);
}

/** Decodes only the canonical hash segment generated by the manifest. */
function decodeArtifactHash(path: string) {
  const encoded = path.slice(LOCAL_PREVIEW_ARTIFACT_PREFIX.length);
  const candidate = encoded.replace("sha256%3A", "sha256:");
  return Schema.decodeOption(Sha256HashSchema)(candidate).pipe(
    Option.filter((hash) => localPreviewArtifactPath(hash) === path)
  );
}

/** Serializes one minimal event from the exact committed manifest. */
function eventJson(manifest: LocalPreviewManifest) {
  return JSON.stringify(
    PreviewEventSchema.make({
      format: LOCAL_PREVIEW_FORMAT,
      revision: manifest.revision,
      route: previewDocumentRoute(manifest.document),
      status: manifest.status,
    })
  );
}

/** Creates the authenticated request transport around scoped provider state. */
export function makePreviewHttp(input: PreviewHttpInput): PreviewHttp {
  const clients = new Map<ServerResponse, ReturnType<typeof setInterval>>();

  /** Handles one authenticated request against one atomic state snapshot. */
  const handle: PreviewHttp["handle"] = (request, response) => {
    if (!hasValidToken(request.headers.authorization, input.token)) {
      writeJson(response, 401, '{"error":"unauthorized"}');
      return;
    }
    if (request.method !== "GET") {
      response.setHeader("allow", "GET");
      writeJson(response, 405, '{"error":"method"}');
      return;
    }
    const path = requestPath(request);
    const state = input.readState();
    if (path === PREVIEW_MANIFEST_PATH) {
      writeJson(response, 200, state.manifestJson);
      return;
    }
    if (path === PREVIEW_EVENTS_PATH) {
      response.writeHead(200, {
        "cache-control": "no-store",
        connection: "keep-alive",
        "content-type": "text/event-stream; charset=utf-8",
      });
      const heartbeat = setInterval(
        () => response.write(PREVIEW_HEARTBEAT),
        input.heartbeatIntervalMs ?? PREVIEW_HEARTBEAT_INTERVAL_MS
      );
      clients.set(response, heartbeat);
      response.once("close", () => {
        clearInterval(heartbeat);
        clients.delete(response);
      });
      response.write(`event: update\ndata: ${eventJson(state.manifest)}\n\n`);
      return;
    }
    if (path.startsWith(LOCAL_PREVIEW_ARTIFACT_PREFIX)) {
      const artifact = decodeArtifactHash(path).pipe(
        Option.flatMap((hash) => HashMap.get(state.artifacts, hash))
      );
      if (Option.isSome(artifact)) {
        writeJson(response, 200, artifact.value);
        return;
      }
      writeJson(response, 409, '{"error":"409"}');
      return;
    }
    writeJson(response, 404, '{"error":"404"}');
  };

  /** Ends every event response without retaining stale scoped clients. */
  const close = () => {
    for (const [client, heartbeat] of clients) {
      clearInterval(heartbeat);
      client.end();
    }
    clients.clear();
  };

  /** Notifies every live client after one complete state replacement. */
  const publish = (state: PreviewHttpState) => {
    const event = `event: update\ndata: ${eventJson(state.manifest)}\n\n`;
    for (const client of clients.keys()) {
      client.write(event);
    }
  };

  return { close, handle, publish };
}
